name: spotify
version: "1.0.0"
config-version: 2

profile: spotify

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - target
  - dbt_packages

models:
  spotify:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: table
